name: Test Action
on:
    workflow_dispatch:
        inputs:
            BUILD_NAME:
                type: choice
                description: 'BUILD_NAME'
                required: true
                options:
                - foo
                - bar
            failOnXrayResults:
                type: choice
                description: 'Fail if XRAY reports issues'
                required: true
                options:
                - true
                - false

jobs:
    test:
        runs-on: ubuntu-latest
        name: test
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: do test
              id: do_test
              uses: ./
              with:
                XRAY_RESULTS_JSON_FILE: ./test/xray_test.json
                BUILD_NAME: ${{ github.event.inputs.BUILD_NAME }}
                BUILD_NUMBER: 1
                FAIL_BUILD: ${{ github.event.inputs.failOnXrayResults == 'true' }}
                ISSUE_URL_TEMPLATE: https://github.com/myorg/repo/issues/new?template=JFrog_exception_request.yml&title=My+Exception+Request+for+{build_name}+(build_number}+{cve_id}&business_unit=someunit&build_name={build_name}&build_number={build_number}&violation_id={violation_id}&business_justification={possible_reason}&build_repository=[]


            

